on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Video Converter Action
      uses: umuthan/video-converter@v1.0
      with:
        videos-folder: 'videos' # This is a Required field & this folder has original images
        new-format: 'mp4' # This is Required field
        output-folder: 'output' # This is Required field & this folder w
